name: CSV Lint

on: [push, pull_request]

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        # checkout v5
        uses: actions/checkout@v4

      - name: Lint CSV files
        # csvlinter-action v1.0.1
        uses: csvlinter/csvlinter-action@eb248038c8222e82b83f9585233f308780c2147b
        with:
          paths: 'Dokumentation/namespaces/*.csv'
          csvlinter_version: 'v1.7.3'
          delimiter: ';'

      - name: find run.sh
        if: always()
        run: find . -name "run.sh"

      - name: list directories
        if: always()
        run: ls -la
